name: Run Python Command

on:
  push:
    branches:
      - main

jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          add-path: true

      - name: Install dependencies
        run: pip install -r requirements.txt  # Replace with your actual dependencies

      - name: Run Python Command with Env Variables
        env:
          dpyToken: os.getenv('DPYTOKEN')
        run: python bot.py
